### ISSUE TITLE
TileEntitySneaky throwing exceptions

### ISSUE THREAD

**Issue by glyphtheory** [Darkhax-Minecraft/Dark-Utilities#16]
`[Server thread/ERROR] [FML]: A TileEntity type net.darkhax.darkutils.features.sneaky.TileEntitySneaky has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.NullPointerException
	at net.darkhax.darkutils.features.sneaky.TileEntitySneaky.writeNBT(TileEntitySneaky.java:40) ~[TileEntitySneaky.class:?]
	at net.darkhax.bookshelf.tileentity.TileEntityBasic.func_189515_b(TileEntityBasic.java:23) ~[TileEntityBasic.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:384) [atj.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:175) [atj.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:199) [lr.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186027_a(ChunkProviderServer.java:227) [lr.class:?]
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1012) [ls.class:?]
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:355) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:636) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
`
This same error message is appearing every 45 seconds on my server console, with or without players logged on. Using the very latest: DarkUtilities-1.10.2-1.1.4.88 and Bookshelf-1.10.2-1.4.2.329, Forge 1.10.2-12.18.2.2105, custom modpack with 72 total mods. Any suggestions? Thanks!

**Comment by darkhax** [comment]
Thank you for this report. Based on what I know, this issue is caused by a Sneaky Block being placed in the world, and another player camouflaging it with a block that has since been removed from the pack. This is not a situation I had anticipated, although now that I know of it, it is easy to make it fail gracefully and discard the camouflaged state.

**Comment by glyphtheory** [comment]
That makes perfect sense, I've been punching so many holes in this world by removing dysfunctional mods that I should've guessed that'd be the reason. Thanks so much for your timely and helpful response!
