### ISSUE TITLE
Invalid projectName "darkutils" and gameVersion "1.15.2"!

### ISSUE THREAD

**Issue by JakeMoe** [Darkhax-Minecraft/Dark-Utilities#218]
While looking for other things in my latest.log, found this error in there:

```
[27Jun2020 08:45:33.418] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [darkutils] Starting version check at https://updates.blamejared.com/get?n=darkutils&gv=1.15.2
[27Jun2020 08:45:33.748] [Forge Version Check/WARN] [net.minecraftforge.fml.VersionChecker/]: Failed to process update information
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.Gson.fromJson(Gson.java:899) ~[gson-2.8.0.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:852) ~[gson-2.8.0.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:801) ~[gson-2.8.0.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:773) ~[gson-2.8.0.jar:?]
        at net.minecraftforge.fml.VersionChecker$1.process(VersionChecker.java:214) ~[?:?]
        at java.lang.Iterable.forEach(Iterable.java:75) [?:1.8.0_241]
        at net.minecraftforge.fml.VersionChecker$1.run(VersionChecker.java:157) [?:?]
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385) ~[gson-2.8.0.jar:?]
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183) ~[gson-2.8.0.jar:?]
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[gson-2.8.0.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:887) ~[gson-2.8.0.jar:?]
        ... 6 more
```

When I checked the URL, instead of returning update JSON, it just sent:

`Invalid projectName "darkutils" and gameVersion "1.15.2"!`

**Comment by Darkhax** [comment]
Thanks, this has now been fixed.
