### ISSUE TITLE
Null Charm bug 1.10.2

### ISSUE THREAD

**Issue by Zithorio** [Darkhax-Minecraft/Dark-Utilities#59]
So after a server update I had a null charm inside an extra utils 2 magic bag, upon attempting to take it out, the game crashes with a 'failed to render screen' java error. Happens 100% of the time.

Versions are:
Dark Utilities 1.10.2 - 1.1.7.111

Extra Utils 2 - 1.10.2-1.3.3

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.7.241-universal.jar)
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.4.347.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.65-beta.jar)
  LoadingPlugin (Quark-r1.1-70.jar)
  AppEngCore (appliedenergistics2-rv4-alpha-11.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.9.15.jar)
  TransformerLoader (OpenComputers-MC1.10.2-1.6.2.7.jar)
  Brandon's Core (BrandonsCore-1.10.2-2.1.5.97-universal.jar)
  IC2core (industrialcraft-2-2.6.188-ex110.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 4/8/17 3:02 AM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at net.darkhax.darkutils.features.nullcharm.ItemNullCharm.func_77624_a(ItemNullCharm.java:43)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:614)
	at net.minecraft.client.gui.GuiScreen.func_146285_a(GuiScreen.java:136)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:166)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

[crash-2017-04-08_03.02.03-client.txt](https://github.com/Darkhax-Minecraft/Dark-Utilities/files/907327/crash-2017-04-08_03.02.03-client.txt)

**Comment by darkhax** [comment]
Thanks for reporting the issue. It's related to the tooltip for the null charm. Looks like one of the blocks/items you put in there has been removed from the game. I will try and get a fix out soon.
