### ISSUE TITLE
Client crash when respawning

### ISSUE THREAD

**Issue by codewarrior0** [Darkhax-Minecraft/Dark-Utilities#6]
Crash occured when respawning after death. Does not happen consistently; the crash is concurrency-related.

```
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at net.darkhax.darkutils.handler.ForgeEventHandler.onEntitySpawn(ForgeEventHandler.java:125)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_247_ForgeEventHandler_onEntitySpawn_EntityJoinWorldEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.world.World.func_72838_d(World.java:1122)
	at net.minecraft.client.multiplayer.WorldClient.func_72838_d(WorldClient.java:156)
	at net.minecraft.client.multiplayer.WorldClient.func_72835_b(WorldClient.java:83)


DarkUtils{1.0.0.21} [Dark Utilities] (DarkUtilities-1.8.9-1.0.0.27.jar) 
Forge{11.15.1.1808} [Minecraft Forge] (forge-1.8.9-11.15.1.1808-universal.jar) 
```

**Comment by darkhax** [comment]
I believe this issue was fixed during the initial 1.9 port. If it still happens, let me know with an updated crash log.
