### ISSUE TITLE
Crash with tether sometime

### ISSUE THREAD

**Issue by jubalearly** [Darkhax-Minecraft/Dark-Utilities#68]
Crashes game, usually have to reenter game in peaceful to get save to load.

The basics, pastebin below

Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.util.math.AxisAlignedBB.func_72326_a(SourceFile:282)
	at net.darkhax.darkutils.features.endertether.TileEntityEnderTether.isEntityCloseEnough(TileEntityEnderTether.java:24)
	at net.darkhax.darkutils.features.endertether.FeatureEnderTether.onEnderTeleport(FeatureEnderTether.java:79)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_130_FeatureEnderTether_onEnderTeleport_EnderTeleportEvent.invoke(.dynamic)

**### https://pastebin.com/KXL0pbVH**

**Comment by EmosewaGamer** [comment]
Yup, I get the same.

**Comment by DV666** [comment]
Same issue for me, server crash after one minute (something like that... time to activate ender tether i suppose).

I disable this item on config and no crash anymore. Waiting for a fix ^^

**Comment by darkhax** [comment]
This was fixed in 1.11.2. A 1.10.2 fix may be coming soon.
