### ISSUE TITLE
Server Crashes With Ender Tether

### ISSUE THREAD

**Issue by SevenMode** [Darkhax-Minecraft/Dark-Utilities#83]
Edit: Using Direwolf20 mod pack v1.11.0, mod version 1.1.8.finalrc1

The server crashed when an Enderman teleported near an Ender Tether, and the error what NullpointerException.
Here's the LOG:
`[01:52:48] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:715) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) ~[ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
	at net.minecraft.util.math.AxisAlignedBB.func_72326_a(SourceFile:238) ~[bby.class:?]
	at net.darkhax.darkutils.features.endertether.TileEntityEnderTether.isEntityCloseEnough(TileEntityEnderTether.java:24) ~[TileEntityEnderTether.class:?]
	at net.darkhax.darkutils.features.endertether.FeatureEnderTether.onEnderTeleport(FeatureEnderTether.java:76) ~[FeatureEnderTether.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_277_FeatureEnderTether_onEnderTeleport_EnderTeleportEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) ~[EventBus.class:?]
	at net.minecraft.entity.monster.EntityEnderman.func_70825_j(EntityEnderman.java:271) ~[yq.class:?]
	at net.minecraft.entity.monster.EntityEnderman.func_70820_n(EntityEnderman.java:254) ~[yq.class:?]
	at net.minecraft.entity.monster.EntityEnderman.func_70097_a(EntityEnderman.java:356) ~[yq.class:?]
	at net.minecraft.entity.EntityLivingBase.func_180430_e(EntityLivingBase.java:1205) ~[sf.class:?]
	at net.minecraft.block.Block.func_180658_a(Block.java:807) ~[akf.class:?]
	at net.minecraft.entity.Entity.func_184231_a(Entity.java:1007) ~[rw.class:?]
	at net.minecraft.entity.EntityLivingBase.func_184231_a(EntityLivingBase.java:205) ~[sf.class:?]
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:795) ~[rw.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70612_e(EntityLivingBase.java:1795) ~[sf.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2217) ~[sf.class:?]
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577) ~[sg.class:?]
	at net.minecraft.entity.monster.EntityMob.func_70636_d(SourceFile:47) ~[yx.class:?]
	at net.minecraft.entity.monster.EntityEnderman.func_70636_d(EntityEnderman.java:225) ~[yq.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013) ~[sf.class:?]
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295) ~[sg.class:?]
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:52) ~[yx.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:1964) ~[aid.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839) ~[ls.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:1934) ~[aid.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1750) ~[aid.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620) ~[ls.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) ~[MinecraftServer.class:?]
	... 4 more
[01:52:48] [Server thread/ERROR]: This crash report has been saved to:`

**Comment by darkhax** [comment]
This is a duplicate issue and fixed in finalrc2.

**Comment by SevenMode** [comment]
Ok thank you
