### ISSUE TITLE
[1.10.2] Issue with the timer and the anti slime block

### ISSUE THREAD

**Issue by darkhax** [Darkhax-Minecraft/Dark-Utilities#86]
Timer and anti slime block conflicting?

```
[22:02:40] [Server thread/WARN] [Bookshelf/]: A TileEntity at %s in world %s failed a client update tick!
java.lang.IllegalArgumentException: Cannot set property PropertyBool{name=powered, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in BlockStateContainer{block=darkutils:anti_slime, properties=[]}
    at pl.asie.foamfix.common.FoamyBlockState.func_177226_a(FoamyBlockState.java:27) ~[foamfix-0.6.3-anarchy.jar:?]
    at net.darkhax.darkutils.features.timer.TileEntityTimer.onEntityUpdate(TileEntityTimer.java:40) ~[TileEntityTimer.class:?]
    at net.darkhax.bookshelf.tileentity.TileEntityBasicTickable.func_73660_a(TileEntityBasicTickable.java:16) [TileEntityBasicTickable.class:?]
    at net.minecraft.world.World.func_72939_s(World.java:1804) [aid.class:?]
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620) [ls.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

**Comment by darkhax** [comment]
This issue was caused by a corrupted world file.
